# Generated by Django 4.2.7 on 2023-12-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_bilmadim_team_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Blog/img')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
