# Generated by Django 4.2.7 on 2023-12-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
